version: '3.8'

services:
  node-app:
    container_name: 'node-app'
    build: ./
    ports: 
      - '80:3000'
  mongo:
    container_name: mongo
    image: 'mongo:latest'
    ports:
      - '27017:27017'